version: "3"

services:
  ui:
    container_name: ui
    image: ui
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - '58000:3000'

  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    ports:
      - '59000:8080'
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:13.3
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
    ports:
      - '5432:5432'