version: "3"

services:
  ui:
    container_name: ui
    image: ui
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - '3000:3000'

  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    volumes:
      - .:/workspace
    ports:
      - '8080:8080'

  db:
    container_name: database
    image: postgres:13.3
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
