version: "3"

services:
  ui:
    image: ep/frontend
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    ports:
      - '58000:3000'

  api:
    image: ep/backend
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    ports:
      - '59000:8080'
    depends_on:
      - database
  database:
    image: postgres:10.5
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOSTNAME
      - POSTGRES_PORT
      - POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 #    - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql