version: "3"

services:
  ui:
    container_name: ui
    image: ui
    build:
      context: .
      dockerfile: ./services/ui/Dockerfile
    ports:
      - '58000:3000'

  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    ports:
      - '59000:8080'
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:10.5
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOSTNAME
      - POSTGRES_PORT
      - POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./server/go_events.sql:/docker-entrypoint-event_planning.d/server/go_events.sql